name: muse
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '3.4.3'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0

  provider: ^6.0.0
  bloc: 
  flutter_bloc: 
  equatable:

  record:
  audioplayers:
  pitch_detector_dart:
  pitchupdart:

  permission_handler:

  buffered_list_stream:

  path_provider:
  sqflite:
  file_picker:

  path:

  tracks_api:
    path: packages/tracks_api
  local_storage_tracks_api:
    path: packages/local_storage_tracks_api
  tracks_repository:
    path: packages/tracks_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/audio/metronome_base.mp3
    - assets/audio/metronome_high.mp3
